export const pgColumnTypes = [
  'bigint',
  'bigserial',
  'bit',
  'bit varying',
  'boolean',
  'box',
  'bytea',
  'character',
  'character varying',
  'cidr',
  'circle',
  'date',
  'double precision',
  'inet',
  'integer',
  'interval',
  'json',
  'jsonb',
  'line',
  'lseg',
  'macaddr',
  'money',
  'numeric',
  'path',
  'pg_lsn',
  'point',
  'polygon',
  'real',
  'smallint',
  'smallserial',
  'serial',
  'text',
  'time',
  'timestamp',
  'timestamp with time zone',
  'tsquery',
  'tsvector',
  'txid_snapshot',
  'uuid',
  'xml',
] as const
export type PgColumnType = (typeof pgColumnTypes)[number]
