export const colorNames: Record<string, string> = {
  ['red']: 'Red',
  ['orange']: 'Orange',
  ['amber']: 'Amber',
  ['yellow']: 'Yellow',
  ['lime']: 'Lime',
  ['green']: 'Green',
  ['emerald']: 'Emerald',
  ['teal']: 'Teal',
  ['cyan']: 'Cyan',
  ['sky']: 'Sky',
  ['blue']: 'Blue',
  ['indigo']: 'Indigo',
  ['violet']: 'Violet',
  ['purple']: 'Purple',
  ['fuchsia']: 'Fuchsia',
  ['pink']: 'Pink',
  ['rose']: 'Rose',
}